version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rustler
      POSTGRES_PASSWORD: rustler
      POSTGRES_DB: rustler
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rustler"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rustler:local
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://rustler:rustler@db/rustler
      PORT: 3000
      HOST: 0.0.0.0
      RUST_LOG: info
    ports:
      - "3000:3000"

volumes:
  postgres_data:
