name: Build and Publish Release Container

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., v1.2.3). If empty, uses the release tag when triggered by a release."
        required: false
        default: ""

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            VER="${{ inputs.version }}"
          else
            VER="${{ github.event.release.tag_name }}"
          fi
          # Fallback if neither is available (e.g., manual dispatch w/o input)
          if [ -z "$VER" ]; then
            VER="${{ github.ref_name }}"
          fi
          echo "ver=$VER" >> $GITHUB_OUTPUT

      - name: Compute image name (lowercase)
        id: repo
        run: |
          echo "name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.name }}
          tags: |
            type=raw,value=${{ steps.version.outputs.ver }}
            type=semver,pattern={{version}},value=${{ steps.version.outputs.ver }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.ver }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.ver }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' && github.event.action == 'published' }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description=Rustler personal finance application

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
