name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write  # needed to create releases/tags
  pull-requests: write  # needed to open/maintain release PRs

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          package-name: rustler
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"perf","section":"Performance Improvements","hidden":false},
             {"type":"refactor","section":"Refactoring","hidden":false},
             {"type":"revert","section":"Reverts","hidden":false},
             {"type":"docs","section":"Documentation","hidden":false},
             {"type":"style","section":"Styles","hidden":true},
             {"type":"chore","section":"Chores","hidden":true},
             {"type":"test","section":"Tests","hidden":true}]
        # If a release was created, release-please will emit outputs we can consume in dependent workflows.
